# Site Settings
title: "PitBull Terrier Devlog"
name: "pitbull terrier"
description: "만약 노력이 재능이리면, 내 재능은 어딜가도 꿀리지 않는다"
url: "https://yoonbitnara.github.io"
baseurl: ""

# Profile Settings
avatar: "/assets/images/main_img.PNG"
bio: "만약 노력이 재능이리면, 내 재능은 어딜가도 꿀리지 않는다"
location: "South Korea"
email: "ybnr92@gmail.com"

# Pagination - disabled to load all posts
# paginate: 1000
# paginate_path: "/page:num/"

# Social Links
social:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/yoonbitnara"
  - name: "Email"
    icon: "fas fa-envelope"
    url: "mailto:ybnr92@gmail.com"

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Asia/Seoul

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "pitbull terrier"
      comments: true
      share: true
      related: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE